# https://taskfile.dev

version: '3'

tasks:
  build lin:
    desc: Build the Linux binary
    cmds:
      - go build -o bin/locc . -ldflags="-s -w"
    env:
      GOOS: linux
      GOARCH: amd64
  build win:
    desc: Build the Windows binary
    cmds:
      - go build -o bin/locc.exe . -ldflags="-s -w"
    env:
      GOOS: windows
      GOARCH: amd64
  locc:
    desc: Run locc
    cmds:
      - task build windows
    env:
      GOOS: windows
      GOARCH: amd64
