# https://taskfile.dev

version: '3'

tasks:
  build linux:
    desc: Build the Linux binary
    cmds:
      - go build -o bin/hello-linux ./cmd/locc.exe
    env:
      GOOS: linux
      GOARCH: amd64
  build windows:
    desc: Build the Windows binary
    cmds:
      - go build -o bin/hello-windows.exe ./cmd/locc.exe
    env:
      GOOS: windows
      GOARCH: amd64
