# https://taskfile.dev

version: '3'

tasks:
  build:lin:
    desc: Build the Linux binary
    cmds:
      - golangci-lint run
      - go build -ldflags="-s -w" -o bin/locc . 
    env:
      GOOS: linux
      GOARCH: amd64

  build:lin:32:
    desc: Build the Linux binary
    cmds:
      - golangci-lint run
      - go build -ldflags="-s -w" -o bin/locc-x32 .
    env:
      GOOS: linux
      GOARCH: 386 # x86

  build:win:
    desc: Build the Windows binary
    cmds:
      - golangci-lint run
      - go build -ldflags="-s -w" -o bin/locc.exe .
    env:
      GOOS: windows
      GOARCH: amd64

  build:win:32:
    desc: Build the Windows binary
    cmds:
      - golangci-lint run
      - go build -ldflags="-s -w" -o bin/locc-x32.exe .
    env:
      GOOS: windows
      GOARCH: 386 # x86
  
  build:all:
    desc: Build all binaries
    cmds:
      - task build:lin
      - task build:lin:32
      - task build:win
      - task build:win:32

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  fmt: 
    desc: Run go fmt
    cmds:
      - golangci-lint fmt 

  tidy:
    desc: Tidy up go.mod and go.sum
    cmds:
      - go mod tidy

