# https://taskfile.dev

version: '3'

tasks:
  build:lin:
    desc: Build the Linux binary
    cmds:
      - golangci-lint run
      - go build -ldflags="-s -w" -o bin/locc ./src 
    env:
      GOOS: linux
      GOARCH: amd64
  build:win:
    desc: Build the Windows binary
    cmds:
      - golangci-lint run
      - go build -ldflags="-s -w" -o bin/locc.exe ./src
    env:
      GOOS: windows
      GOARCH: amd64
  lint:
    desc: Run linters
    cmds:
      - golangci-lint run
  fmt: 
    desc: Run go fmt
    cmds:
      - golangci-lint fmt 
