package helpers

type LanguageMeta struct {
	Ext   string
	Lang  string
	Color string
}

var Languages = []LanguageMeta{
	{".txt", "Text", Gray},
	{".go", "Go", Cyan},
	{".js", "JavaScript", Yellow},
	{".cjs", "CommonJS", Yellow},
	{".mjs", "ESModule", Yellow},
	{".ts", "TypeScript", Blue},
	{".tsx", "TSX", Blue},
	{".jsx", "JSX", Yellow},
	{".py", "Python", Yellow},
	{".sh", "Shell", Green},
	{".rb", "Ruby", Red},
	{".rs", "Rust", Red},
	{".c", "C", Gray},
	{".cpp", "C++", Gray},
	{".cs", "C#", Magenta},
	{".java", "Java", Magenta},
	{".php", "PHP", Blue},
	{".html", "HTML", Yellow},
	{".htm", "HTML", Yellow},
	{".xml", "XML", Yellow},
	{".css", "CSS", Green},
	{".scss", "SCSS", Green},
	{".json", "JSON", Gray},
	{".jsonc", "JSONC", Cyan},
	{".json5", "JSON5", Cyan},
	{".toml", "TOML", Gray},
	{".ini", "INI", Gray},
	{".yml", "YAML", Gray},
	{".yaml", "YAML", Gray},
	{".md", "Markdown", Gray},
	{".vue", "Vue", Green},
	{".gd", "GDScript", Magenta},
	{".gitignore", "Gitignore", Orange},
	{".dockerignore", "Dockerignore", Blue},
	{".loccignore", "Loccignore", Orange},
	{".log", "Log", Gray},
	{".lock", "Lockfile", Gray},
	{".ps1", "PowerShell", Blue},
	{".psm1", "PowerShell Module", Magenta},
}

var CommentMarkers = map[string]string{
	".go":           "//",
	".js":           "//",
	".cjs":          "//",
	".mjs":          "//",
	".ts":           "//",
	".tsx":          "//",
	".jsx":          "//",
	".py":           "#",
	".sh":           "#",
	".rb":           "#",
	".rs":           "//",
	".c":            "//",
	".cpp":          "//",
	".cs":           "//",
	".java":         "//",
	".php":          "//",
	".html":         "<!--",
	".xml":          "<!--",
	".css":          "/*",
	".scss":         "/*",
	".json":         "",
	".jsonc":        "//",
	".json5":        "//",
	".toml":         "#",
	".ini":          ";",
	".yml":          "#",
	".yaml":         "#",
	".md":           "<!--",
	".vue":          "//",
	".gd":           "#",
	".gitignore":    "#",
	".dockerignore": "#",
	".loccignore":   "#",
}

var BINARY_EXTENSIONS = []string{
	"**/*.exe",
	"**/*.dll",
	"**/*.so",
	"**/*.dylib",
	"**/*.o",
	"**/*.a",
	"**/*.lib",
	"**/*.class",
	"**/*.jar",
	"**/*.pyc",
	"**/*.pyo",
	"**/*.jpg",
	"**/*.png",
	"**/*.gif",
	"**/*.svg",
	"**/*.ico",
	"**/*.webp",
	"**/*.mp4",
	"**/*.mp3",
	"**/*.wav",
	"**/*.flac",
	"**/*.avi",
	"**/*.mkv",
	"**/*.mov",
	"**/*.wmv",
	"**/*.zip",
	"**/*.tar.gz",
	"**/*.tar.bz2",
	"**/*.rar",
	"**/*.7z",
	"**/*.gz",
	"**/*.bz2",
	"**/*.xz",
	"**/*.zst",
}
